# Generated by Django 4.0.5 on 2022-06-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'due_back'], 'verbose_name': 'Копия', 'verbose_name_plural': 'Копии книг'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='surname',
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0064cc58-6f83-4bfa-9a70-2838abf0706f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(default='yes', max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], default='Male', max_length=7, verbose_name='Пол'),
        ),
    ]
