# Generated by Django 4.0.5 on 2022-06-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_bookinstance_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['user'], 'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0b13a1d-55b7-4387-9346-796d2490e865'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ages',
            field=models.IntegerField(default=16, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='number_of_passport',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='place',
            field=models.CharField(max_length=30, null=True, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
