# Generated by Django 4.0.5 on 2022-07-11 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookinstance_options_alter_bookinstance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='day_borrower',
            field=models.DateField(null=True, verbose_name='Дата выдачи в пользование'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9ebcdc4-3a85-4414-834f-71758f2061dd'), primary_key=True, serialize=False),
        ),
    ]
